import {
  LayoutDashboard,
  School,
  GraduationCap,
  Users,
  UserRound,
  ClipboardCheck,
  CalendarDays,
  FileSpreadsheet,
  Wallet,
  BookOpen,
  Bell,
  Bus,
  Library,
  Inbox,
  Calendar,
  FileBarChart,
  Settings,
  Building2,
  BookMarked,
  MessageSquareWarning,
  BadgeCheck,
} from 'lucide-react';

export const NAV = {
  super_admin: [
    { to: '/', labelKey: 'nav.dashboard', icon: LayoutDashboard },
    { to: '/schools', labelKey: 'nav.schools', icon: School },
  ],
  school_admin: [
    { to: '/', labelKey: 'nav.dashboard', icon: LayoutDashboard },
    { to: '/setup', labelKey: 'nav.setup', icon: Settings },
    { to: '/academic', labelKey: 'nav.academic', icon: BookMarked },
    { to: '/students', labelKey: 'nav.students', icon: GraduationCap },
    { to: '/teachers', labelKey: 'nav.teachers', icon: Users },
    { to: '/parents', labelKey: 'nav.parents', icon: UserRound },
    { to: '/admissions', labelKey: 'nav.admissions', icon: Inbox },
    { to: '/attendance', labelKey: 'nav.attendance', icon: ClipboardCheck },
    { to: '/timetable', labelKey: 'nav.timetable', icon: CalendarDays },
    { to: '/exams', labelKey: 'nav.exams', icon: FileSpreadsheet },
    { to: '/fees', labelKey: 'nav.fees', icon: Wallet },
    { to: '/homework', labelKey: 'nav.homework', icon: BookOpen },
    { to: '/library', labelKey: 'nav.library', icon: Library },
    { to: '/transport', labelKey: 'nav.transport', icon: Bus },
    { to: '/notices', labelKey: 'nav.notices', icon: Bell },
    { to: '/events', labelKey: 'nav.events', icon: Calendar },
    { to: '/leaves', labelKey: 'nav.leaves', icon: BadgeCheck },
    { to: '/complaints', labelKey: 'nav.complaints', icon: MessageSquareWarning },
    { to: '/reports', labelKey: 'nav.reports', icon: FileBarChart },
  ],
  teacher: [
    { to: '/', labelKey: 'nav.dashboard', icon: LayoutDashboard },
    { to: '/attendance', labelKey: 'nav.attendance', icon: ClipboardCheck },
    { to: '/homework', labelKey: 'nav.homework', icon: BookOpen },
    { to: '/exams', labelKey: 'nav.marks', icon: FileSpreadsheet },
    { to: '/timetable', labelKey: 'nav.timetable', icon: CalendarDays },
    { to: '/leaves', labelKey: 'nav.leaves', icon: BadgeCheck },
    { to: '/notices', labelKey: 'nav.notices', icon: Bell },
  ],
  parent: [
    { to: '/', labelKey: 'nav.home', icon: LayoutDashboard },
    { to: '/attendance', labelKey: 'nav.attendance', icon: ClipboardCheck },
    { to: '/fees', labelKey: 'nav.fees', icon: Wallet },
    { to: '/homework', labelKey: 'nav.homework', icon: BookOpen },
    { to: '/exams', labelKey: 'nav.results', icon: FileSpreadsheet },
    { to: '/timetable', labelKey: 'nav.timetable', icon: CalendarDays },
    { to: '/notices', labelKey: 'nav.notices', icon: Bell },
    { to: '/events', labelKey: 'nav.events', icon: Calendar },
  ],
  student: [
    { to: '/', labelKey: 'nav.home', icon: LayoutDashboard },
    { to: '/homework', labelKey: 'nav.homework', icon: BookOpen },
    { to: '/exams', labelKey: 'nav.results', icon: FileSpreadsheet },
    { to: '/timetable', labelKey: 'nav.timetable', icon: CalendarDays },
    { to: '/attendance', labelKey: 'nav.attendance', icon: ClipboardCheck },
    { to: '/notices', labelKey: 'nav.notices', icon: Bell },
  ],
  accountant: [
    { to: '/', labelKey: 'nav.dashboard', icon: LayoutDashboard },
    { to: '/fees', labelKey: 'nav.fees', icon: Wallet },
    { to: '/reports', labelKey: 'nav.reports', icon: FileBarChart },
  ],
  receptionist: [
    { to: '/', labelKey: 'nav.dashboard', icon: LayoutDashboard },
    { to: '/admissions', labelKey: 'nav.admissions', icon: Inbox },
    { to: '/students', labelKey: 'nav.students', icon: GraduationCap },
  ],
  librarian: [
    { to: '/', labelKey: 'nav.dashboard', icon: LayoutDashboard },
    { to: '/library', labelKey: 'nav.library', icon: Library },
  ],
};

NAV.principal = NAV.school_admin;

export { Building2 };
